### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Tocmac** [zye1996/3DSSD-torch#3]
Hello, I have successfully configured the environment, but when I trained on the server, I was reported the following error:
>train: 100%|██████████| 441/441 [06:03<00:00,  1.39it/s, total_it=882]
epochs:   1%|          | 1/120 [12:11<12:10:14, 368.19s/it, total_loss=1.8]
epochs:   1%|          | 1/120 [12:11<12:10:14, 368.19s/it, total_loss=1.8]

>eval:   0%|          | 0/111 [00:00<?, ?it/s]
epochs:   1%|          | 1/120 [12:18<24:24:44, 738.53s/it, total_loss=1.8]

>Traceback (most recent call last):
  File "lib/core/trainer.py", line 238, in <module>
    cur_trainer.train()
  File "lib/core/trainer.py", line 194, in train
    self.val()
  File "lib/core/trainer.py", line 209, in val
    end_points = post_process(end_points)
  File "/data0/3DSSD-torch/lib/modeling/single_stage_detector.py", line 304, in post_process
    pred_score = end_points['post_pred_score']
KeyError: 'post_pred_score'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1134, in __del__
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1281, in close
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1467, in display
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1137, in __repr__
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1424, in format_dict
TypeError: 'NoneType' object is not iterable

I would appreciate it if you could give me some help.

**Comment by zye1996** [comment]
I am sorry I made a mistake in trainer.py where the validation is performed. I have pushed the commit to comment those lines out and I will push another to do eval during training. Now you can only eval after finishing training.

**Comment by Tocmac** [comment]
> I am sorry I made a mistake in trainer.py where the validation is performed. I have pushed the commit to comment those lines out and I will push another to do eval during training. Now you can only eval after finishing training.

Thank you so much !

**Comment by zye1996** [comment]
> > I am sorry I made a mistake in trainer.py where the validation is performed. I have pushed the commit to comment those lines out and I will push another to do eval during training. Now you can only eval after finishing training.
> 
> Thank you so much !

codebase updated, issue closed
