### ISSUE TITLE
Nuscenes implementation

### ISSUE THREAD

**Issue by pigtigger** [zye1996/3DSSD-torch#7]
Hey @zye1996 , this repo is a great work !  and i m wondering if it is convenient for you to update some guidance to train 3dssd on Nuscenes, as i find some nuscenes configs already in tools/cfgs. is it on your roadmap?

**Comment by zye1996** [comment]
> Hey @zye1996 , this repo is a great work ! and i m wondering if it is convenient for you to update some guidance to train 3dssd on Nuscenes, as i find some nuscenes configs already in tools/cfgs. is it on your roadmap?

From the current training result, I cannot reproduce the performance stated by the paper (I get NDS 0.263). It would be great if could try use the configuration to train by yourself and compare the result.

**Comment by sixcomicpen** [comment]
Dear author, how can I solve the following problem：
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux.

**Comment by markwave** [comment]
> Hey @zye1996 , this repo is a great work ! and i m wondering if it is convenient for you to update some guidance to train 3dssd on Nuscenes, as i find some nuscenes configs already in tools/cfgs. is it on your roadmap?

hi,i want to train the nuscens_mini dataset on the 3dssd_diou.yaml on the cfg,but it can runs well ,it will occur the error like this below,how can i fix this?
Error message:"Traceback (most recent call last):
  File "train.py", line 208, in <module>
    main()
  File "train.py", line 67, in main
    args, cfg = parse_config()
  File "train.py", line 56, in parse_config
    cfg_from_yaml_file(args.cfg_file, cfg)
  File "/data/cai/3DSSD/pcdet/config.py", line 78, in cfg_from_yaml_file
    merge_new_config(config=config, new_config=new_config)
  File "/data/cai/3DSSD/pcdet/config.py", line 52, in merge_new_config
    if '_BASE_CONFIG_' in new_config:
TypeError: argument of type 'NoneType' is not iterable
"
